name: Sequential Jobs Workflow

on:
  push:
    branches:
      - main

jobs:
  job_a:
    name: Job A - Initial Task
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job A
        run: echo "Dies ist Job A"

  job_b:
    name: Job B - Depends on A
    runs-on: ubuntu-latest
    needs: job_a
    steps:
      - name: Echo Job B
        run: echo "Dies ist Job B"

  job_c:
    name: Job C - Depends on B
    runs-on: ubuntu-latest
    needs: job_b
    steps:
      - name: Echo Job C
        run: echo "Dies ist Job C"
